apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-journey-deployment
  namespace: web-app-devops
  labels:
    release: my-monitor
spec:
  selector:
    matchLabels:
      app: web-site
  template:
    metadata:
      labels:
        app: web-site
      containers:
        - name: my-web-container
          image: my-devops-journey:v7
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10005
            runAsGroup: 10005
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
              ephemeral-storage: "50Mi"
            limits:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
