apiVersion: v1
kind: Service
metadata:
  name: devops-journey-service
  namespace: web-app-devops
  labels:
    release: my-monitor
spec:
  type: NodePort
  selector:
    app: web-site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
