name: CI Syntax Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Kubernetes manifests (Lint)
        run: |
          docker run --rm -v ${{ github.workspace }}/k8s:/project zegl/kube-score:latest score /project/deployment.yaml /project/service.yaml /project/hpa.yaml /project/ingress.yaml
