name: CI Syntax Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Kube-Score
        uses: zegl/kube-score-action-github@v1
        with:
          manifests: k8s/*.yaml
