name: CI Syntax Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Run Kube-Score
        run: |
          # 1. Download the latest binary for Linux
          curl -LO https://github.com/zegl/kube-score/releases/download/v1.18.0/kube-score_1.18.0_linux_amd64.tar.gz

          # 2. Extract the binary
          tar -xzf kube-score_1.18.0_linux_amd64.tar.gz
          chmod +x kube-score

          # 3. Run it against your files
          ./kube-score score k8s/*.yaml
